# Generated by Django 5.2.9 on 2025-12-08 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewTrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('is_category', models.BooleanField(default=False)),
                ('alternate_spellings', models.JSONField(blank=True, null=True)),
                ('hashtags', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_trands', to='newtrand.category')),
            ],
            options={
                'verbose_name': 'NewTrand',
                'verbose_name_plural': 'NewTrands',
                'ordering': ['-created_at', 'word'],
            },
        ),
    ]
